### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kasparsv** [massive/acdc#1]
Hello!

I'm getting error at npm install stage. Nodejs 12.18.1 LTS on MacOS 10.15.5 (Catalina). Any ideas?

```
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2845:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../node-expat.cc:1:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
../../nan/nan_converters_43_inl.h:37:29: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2855:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
In file included from ../node-expat.cc:1:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:5784:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../node-expat.cc:1:
In file included from ../../nan/nan.h:2722:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: 
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../node-expat.cc:1:
In file included from ../../nan/nan.h:2722:
../../nan/nan_object_wrap.h:127:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: 
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../node-expat.cc:1:
In file included from ../../nan/nan.h:2818:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See
      http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:5202:3: note: 'GetContents' has been explicitly marked deprecated
      here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
../node-expat.cc:11:26: error: no template named 'Handle'
  static void Initialize(Handle<Object> target)
                         ^
../node-expat.cc:481:23: error: no template named 'Handle'
  void Emit(int argc, Handle<Value> argv[])
                      ^
../node-expat.cc:29:69: error: too few arguments to function call, single argument 'context' was not specified
    target->Set(Nan::New("Parser").ToLocalChecked(), t->GetFunction());
                                                     ~~~~~~~~~~~~~~ ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:6404:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../node-expat.cc:98:33: error: too few arguments to function call, single argument 'context' was not specified
        str = info[0]->ToString();
              ~~~~~~~~~~~~~~~~~ ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2807:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../node-expat.cc:103:47: error: too few arguments to function call, single argument 'context' was not specified
        Local<Object> obj = info[0]->ToObject();
                            ~~~~~~~~~~~~~~~~~ ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2819:3: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
  ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../node-expat.cc:124:30: error: too few arguments to function call, single argument 'isolate' was not specified
    int len = str.Utf8Length();
              ~~~~~~~~~~~~~~ ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2974:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
../node-expat.cc:130:26: error: cannot initialize a parameter of type 'v8::Isolate *' with an rvalue of type 'char *'
    assert(str.WriteUtf8(static_cast<char *>(buf), len) == len);
                         ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: 
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3034:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
../node-expat.cc:301:13: error: no matching member function for call to 'Set'
      attr->Set(Nan::New(atts1[0]).ToLocalChecked(), Nan::New(atts1[1]).ToLocalChecked());
      ~~~~~~^~~
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/kaspars/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../node-expat.cc:304:5: error: no template named 'Handle'
    Handle<Value> argv[3] = { Nan::New("startElement").ToLocalChecked(),
    ^
../node-expat.cc:317:5: error: no template named 'Handle'
    Handle<Value> argv[2] = { Nan::New("endElement").ToLocalChecked(), Nan::New(name).ToLocalChecked() };
    ^
../node-expat.cc:327:5: error: no template named 'Handle'
    Handle<Value> argv[1] = { Nan::New("startCdata").ToLocalChecked() };
    ^
../node-expat.cc:337:5: error: no template named 'Handle'
    Handle<Value> argv[1] = { Nan::New("endCdata").ToLocalChecked() };
    ^
../node-expat.cc:348:5: error: no template named 'Handle'
    Handle<Value> argv[2] = { Nan::New("text").ToLocalChecked(),
    ^
../node-expat.cc:360:5: error: no template named 'Handle'
    Handle<Value> argv[3] = { Nan::New("processingInstruction").ToLocalChecked(),
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kaspars/Downloads/acdc-master/node_modules/node-expat
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN acdc@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by xorbital** [comment]
```
npm cache clean --force
rm -rf node_modules package-lock.json
npm install
```
worked for me: https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle
