### ISSUE TITLE
unsupported please help me!

### ISSUE THREAD

**Issue by giandomobile** [massive/acdc#4]
coonnecting to: 192.168.86.61
node:internal/tls/secure-context:279
      context.loadPKCS12(toBuf(pfx));
              ^

Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:279:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Object.connect (node:_tls_wrap:1625:48)
    at SamsungAirconditioner.get_token (/root/acdc/node_modules/node-samsung-airconditioner/samsung-airconditioner.js:151:16)
    at SamsungDiscovery.<anonymous> (/root/acdc/lib/aircon.js:54:8)
    at SamsungDiscovery.emit (node:events:513:28)
    at Socket.<anonymous> (/root/acdc/node_modules/node-samsung-airconditioner/samsung-discovery.js:111:10)
    at Socket.emit (node:events:525:35)
    at UDP.onMessage [as onmessage] (node:dgram:922:8)

Node.js v18.7.0

**Comment by giandomobile** [comment]
Plugin find my samsung ac (2878 port) correctly but the code leave me an error, please help me!
